# This workflow will execute a specified python script in this repo

name: Schedule to Calendar

# Controls when the action will run:
# 1. Runs on CRON job (every morning at 6am)
# 2. Runs when manually triggered using the UI or API
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      calendar-name:
        description: 'Name of the calendar'
        default: ''
        required: false
        type: string
      team-url:
        description: 'e.g. "https://sydneysocialbasketball.com.au/team/YOUR-TEAM-NAME/"'
        default: ''
        required: false
        type: string
      color-id:
        description: 'Event color id'
        default: ''
        required: false
        type: string
  schedule:
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-script"
  run-script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GCAL_CLIENT_ID: ${{ secrets.GCAL_CLIENT_ID  }}
      GCAL_CLIENT_SECRET: ${{ secrets.GCAL_CLIENT_SECRET  }}
      GCAL_REFRESH_TOKEN: ${{ secrets.GCAL_REFRESH_TOKEN  }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.8"
      
    - name: Install packages
      run: |
        pip install -r ./requirements.txt
      
    - name: Run script
      run: |
        python ./create_gcal_events.py
