# This workflow will execute a specified python script in this repo

name: Schedule to Calendar

# Controls when the action will run:
# 1. Runs on CRON job (every morning at 6am)
# 2. Runs when manually triggered using the UI or API
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      log-level:
        description: "Log level for action run"
        default: 'INFO'
        type: choice
        options:
          - MAJOR
          - INFO
          - DEBUG
         
  schedule:
    - cron: '0 20 * * *' # Note that this is UTC time, which is our 6am equivalent in NSW, Australia

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GCAL_CLIENT_ID: ${{ secrets.GCAL_CLIENT_ID  }}
      GCAL_CLIENT_SECRET: ${{ secrets.GCAL_CLIENT_SECRET  }}
      GCAL_REFRESH_TOKEN: ${{ secrets.GCAL_REFRESH_TOKEN  }}
      LOG_LEVEL: INFO

    steps:  
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.8"

    - name: Set log level
      run: |
        # Override with if inputs are provided
        if [[ "${{ inputs.log-level }}" != "" ]]; then
          echo "LOG_LEVEL=${{ inputs.log-level }}" >> GITHUB_ENV
        fi

        # Override if runner debug mode is enabled
        if [[ "${{ runner.debug }}" == "1" ]]; then
          echo "LOG_LEVEL=DEBUG" >> GITHUB_ENV
        fi
      
    - name: Install packages
      run: |
        pipenv install
      
    - name: Run script
      run: |
        pipenv run ./create_gcal_events.py
